### ISSUE TITLE
Feature request: minimum cut function

### ISSUE THREAD

**Issue by MrRaghav** [takemaru/graphillion#44]
Hello,
I know that NetworkX has a direct function to implement min cut max flow algorithm ([minimum_cut()](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.flow.minimum_cut.html)). It works well with small graphs but fails for large graphs.

I checked Graphillion and found that it can use graphs from [NetworkX](https://github.com/takemaru/graphillion#working-with-networkx) but I couldn't find a direct minimum_cut() function.

This is a feature request to add this functionality in Graphillion.

**Comment by takemaru** [comment]
Thank you for using Graphillion.

Graphillion is mainly designed for dealing with complex graph constraints, but not for scalability of graph size.
In terms of scalability, Graphillion cannot outperform NetworkX due to the design principle.
Min cut is a simple constraint, solvable in a poly time, so I recommend you to use NetworkX for that.

Best regards,

**Comment by MrRaghav** [comment]
Thank you. I am closing this issue.
